$(document).ready(function () {indexDict['en'] = [{ "title" : "Adaptive Project and Portfolio Management Trial Guide ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide ", 
"snippet" : "This role-based trial guide will assist you and your team through your OnePlan trial. Also see our  full user guides  for more information. OnePlan's Adaptive Project and Portfolio Management solution offers a portfolio and resource management solution that fits the needs of every work team includin...", 
"body" : "This role-based trial guide will assist you and your team through your OnePlan trial. Also see our  full user guides  for more information. OnePlan's Adaptive Project and Portfolio Management solution offers a portfolio and resource management solution that fits the needs of every work team including product teams, PMOs and even service organizations. With OnePlan you can optimize your portfolio and resources enterprise wide. " }, 
{ "title" : "In this section ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide.html#UUID-48439fbd-1753-490d-5893-acbe2c77bbf6_section-idm457337740324643287464074546", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ In this section ", 
"snippet" : "Strategy - Steering Committee Manage corporate strategy Project Management - Project Manager Create a new PlanManage Plan DetailsManage the Work Plan in ListsManage the Work Plan in BoardsManage Resource PlansManage Financial PlansInsights overviewView Reports and DashboardsUpdate Status ReportsPort...", 
"body" : "Strategy - Steering Committee Manage corporate strategy Project Management - Project Manager Create a new PlanManage Plan DetailsManage the Work Plan in ListsManage the Work Plan in BoardsManage Resource PlansManage Financial PlansInsights overviewView Reports and DashboardsUpdate Status ReportsPortfolio Management - Portfolio Manager Monitor and prioritize your Portfolio overviewCapture and prioritize IdeasView Reports and DashboardsInsights overviewResource Management - Resource Manager Resource Center overviewManage resource schedulesManage Resource PlansWork Management - Team Member Update TimesheetsManage My WorkInsights overviewCreate new IdeasReporting - ExecutivesView Reports and Dashboards" }, 
{ "title" : "Strategy - Steering Committee ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/strategy---steering-committee.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Strategy - Steering Committee ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Manage corporate strategy ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/strategy---steering-committee/manage-corporate-strategy.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Strategy - Steering Committee \/ Manage corporate strategy ", 
"snippet" : "Connect long-term business strategy, goals\/OKRs and results to adapt and thrive....", 
"body" : "[video] Connect long-term business strategy, goals\/OKRs and results to adapt and thrive. " }, 
{ "title" : "Project Management - Project Manager ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Create a new Plan ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/create-a-new-plan.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan ", 
"snippet" : "This article explains how to create a new plan.  A \"plan\" is a general term that may be used for something to be managed and\/or analyzed.  Such as projects, epics, portfolios, programs, initiatives, etc.  OnePlan users who are in the permissions groups Contributor, Manager, or Owner can create new p...", 
"body" : "This article explains how to create a new plan.  A \"plan\" is a general term that may be used for something to be managed and\/or analyzed.  Such as projects, epics, portfolios, programs, initiatives, etc.  OnePlan users who are in the permissions groups Contributor, Manager, or Owner can create new plans. " }, 
{ "title" : "Portfolios Page ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2229bde9-013b-b8e7-a54d-b954d457c5ab_id_getting-started-page", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Portfolios Page ", 
"snippet" : "Create a new plan from the Portfolios page. Click the New Plan menu, then select the desired plan type. You may see multiple plan types or just \"New Plan,\" depending how your trial site was set up....", 
"body" : "Create a new plan from the Portfolios page. Click the New Plan menu, then select the desired plan type. You may see multiple plan types or just \"New Plan,\" depending how your trial site was set up. " }, 
{ "title" : "Example Plan Types ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2229bde9-013b-b8e7-a54d-b954d457c5ab_id_example-plan-types", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Portfolios Page \/ Example Plan Types ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Plan Name ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2229bde9-013b-b8e7-a54d-b954d457c5ab_id_plan-name", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Plan Name ", 
"snippet" : "First, enter the new plan name, such as Office365 Launch . Click Add Plan. Then, you will be directed to the Plan Details page....", 
"body" : "First, enter the new plan name, such as Office365 Launch . Click Add Plan. Then, you will be directed to the Plan Details page. " }, 
{ "title" : "Plan Details ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2229bde9-013b-b8e7-a54d-b954d457c5ab_id_new-plan-form", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Plan Details ", 
"snippet" : "Complete the plan's details. Your form may have different fields & different stages, based on your organization's use case & configuration. The page is editable and you may always return to the Details page throughout the life of the plan. When you make a change, it is saved automatically....", 
"body" : "Complete the plan's details. Your form may have different fields & different stages, based on your organization's use case & configuration. The page is editable and you may always return to the Details page throughout the life of the plan. When you make a change, it is saved automatically. " }, 
{ "title" : "Enter Prioritization Fields ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2229bde9-013b-b8e7-a54d-b954d457c5ab_id_enter-prioritization-fields", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Plan Details \/ Enter Prioritization Fields ", 
"snippet" : "For the purpose of later doing prioritization & portfolio analysis, be sure to complete the prioritization fields for your plan. There are traditional prioritization and also SAF agile prioritization type fields....", 
"body" : "For the purpose of later doing prioritization & portfolio analysis, be sure to complete the prioritization fields for your plan. There are traditional prioritization and also SAF agile prioritization type fields. " }, 
{ "title" : "Move Plan to the Next Stage ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2229bde9-013b-b8e7-a54d-b954d457c5ab_id_move-plan-to-the-next-stage", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Plan Details \/ Enter Prioritization Fields \/ Move Plan to the Next Stage ", 
"snippet" : "When ready to move your plan to the next stage, Click on the stage name to visually see the current stage. The tab color changes to green on the current stage. Future stages are grey. Previous stages are blue. You would also want to change the stage field to the appropriate stage. The fields & apps ...", 
"body" : "When ready to move your plan to the next stage, Click on the stage name to visually see the current stage. The tab color changes to green on the current stage. Future stages are grey. Previous stages are blue. You would also want to change the stage field to the appropriate stage. The fields & apps available may be different at each stage of planning. " }, 
{ "title" : "Time to Plan! ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2229bde9-013b-b8e7-a54d-b954d457c5ab_id_build-out-plan", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Time to Plan! ", 
"snippet" : "Build out your plan according to your planning preference. This trial guide will walk you through the following top down planning features: Build a Resource Plan Build a Financial Plan Do portfolio analysis...", 
"body" : "Build out your plan according to your planning preference. This trial guide will walk you through the following top down planning features: Build a Resource Plan Build a Financial Plan Do portfolio analysis " }, 
{ "title" : "Manage Plan Details ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/manage-plan-details.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Manage Plan Details ", 
"snippet" : "Manage your Plans meta data using the Plan Detail form....", 
"body" : "[video] Manage your Plans meta data using the Plan Detail form. " }, 
{ "title" : "Manage the Work Plan in Lists ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists ", 
"snippet" : "To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams....", 
"body" : "To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams. " }, 
{ "title" : "OnePlan's Work Plan ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-b72b176a-7a99-7429-75a5-945ea759915b_section-idm4671155326905632715967479364", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ OnePlan's Work Plan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Microsoft Project Desktop and OnePlan ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-b72b176a-7a99-7429-75a5-945ea759915b_section-idm4483122699662432715968747471", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ Microsoft Project Desktop and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Project for the web and OnePlan ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-b72b176a-7a99-7429-75a5-945ea759915b_section-idm4592941179484832715969732862", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ Project for the web and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Microsoft Planner and OnePlan ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-b72b176a-7a99-7429-75a5-945ea759915b_section-idm459294117542083271597040602", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ Microsoft Planner and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Azure DevOps and OnePlan ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-b72b176a-7a99-7429-75a5-945ea759915b_section-idm4671155347873632715971846753", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ Azure DevOps and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Manage the Work Plan in Boards ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-boards.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Boards ", 
"snippet" : "Visually manage work using Kanban boards with the flexibility to easily model any workflow process, regardless of complexity....", 
"body" : "[video] Visually manage work using Kanban boards with the flexibility to easily model any workflow process, regardless of complexity. " }, 
{ "title" : "Manage Resource Plans ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/manage-resource-plans.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Manage Resource Plans ", 
"snippet" : "Optimize your resource capacity and improve utilization. OnePlan’s Resource Plan delivers a combined view to balance demand and capacity across teams, roles, and named resources....", 
"body" : "[video] Optimize your resource capacity and improve utilization. OnePlan’s Resource Plan delivers a combined view to balance demand and capacity across teams, roles, and named resources. " }, 
{ "title" : "Manage Financial Plans ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/manage-financial-plans.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Manage Financial Plans ", 
"snippet" : "OnePlan connects financials from strategy to investments to detailed budget, actuals, and forecast.  Gain an understanding of project investment to value realization within capital and expense constraints....", 
"body" : "[video] OnePlan connects financials from strategy to investments to detailed budget, actuals, and forecast.  Gain an understanding of project investment to value realization within capital and expense constraints. " }, 
{ "title" : "Insights overview ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/insights-overview.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Insights overview ", 
"snippet" : "OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards....", 
"body" : "[video] OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards. " }, 
{ "title" : "View Reports and Dashboards ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/view-reports-and-dashboards.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ View Reports and Dashboards ", 
"snippet" : "Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions...", 
"body" : "[video] Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions " }, 
{ "title" : "Update Status Reports ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/project-management---project-manager/update-status-reports.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Project Management - Project Manager \/ Update Status Reports ", 
"snippet" : "OnePlan’s Status Reports help you, your stakeholders, and internal team stay honest about your work, process, budgets, and issues....", 
"body" : "[video] OnePlan’s Status Reports help you, your stakeholders, and internal team stay honest about your work, process, budgets, and issues. " }, 
{ "title" : "Portfolio Management - Portfolio Manager ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/portfolio-management---portfolio-manager.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Portfolio Management - Portfolio Manager ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Monitor and prioritize your Portfolio overview ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/portfolio-management---portfolio-manager/monitor-and-prioritize-your-portfolio-overview.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Portfolio Management - Portfolio Manager \/ Monitor and prioritize your Portfolio overview ", 
"snippet" : "Translate strategy into delivery on an organization-wide, cross-functional scale with a portfolio that connect the investments, outcomes, business capabilities, milestones, technology and financials required to realize strategies....", 
"body" : "[video] Translate strategy into delivery on an organization-wide, cross-functional scale with a portfolio that connect the investments, outcomes, business capabilities, milestones, technology and financials required to realize strategies. " }, 
{ "title" : "View Reports and Dashboards ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/portfolio-management---portfolio-manager/view-reports-and-dashboards.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Portfolio Management - Portfolio Manager \/ View Reports and Dashboards ", 
"snippet" : "Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions...", 
"body" : "[video] Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions " }, 
{ "title" : "Insights overview ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/portfolio-management---portfolio-manager/insights-overview.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Portfolio Management - Portfolio Manager \/ Insights overview ", 
"snippet" : "OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards....", 
"body" : "[video] OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards. " }, 
{ "title" : "Resource Management - Resource Manager ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/resource-management---resource-manager.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Resource Management - Resource Manager ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Manage Resource Plans ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/resource-management---resource-manager/manage-resource-plans.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Resource Management - Resource Manager \/ Manage Resource Plans ", 
"snippet" : "Optimize your resource capacity and improve utilization. OnePlan’s Resource Plan delivers a combined view to balance demand and capacity across teams, roles, and named resources....", 
"body" : "[video] Optimize your resource capacity and improve utilization. OnePlan’s Resource Plan delivers a combined view to balance demand and capacity across teams, roles, and named resources. " }, 
{ "title" : "Manage resource schedules ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/resource-management---resource-manager/manage-resource-schedules.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Resource Management - Resource Manager \/ Manage resource schedules ", 
"snippet" : "Proactively identify resource bottlenecks by role, business unit and other key factors to uncover issues before impacting the plan....", 
"body" : "[video] Proactively identify resource bottlenecks by role, business unit and other key factors to uncover issues before impacting the plan. " }, 
{ "title" : "Resource Center overview ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/resource-management---resource-manager/resource-center-overview.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Resource Management - Resource Manager \/ Resource Center overview ", 
"snippet" : "Invite users and manage a pool of resource using the Resource Center...", 
"body" : "[video] Invite users and manage a pool of resource using the Resource Center " }, 
{ "title" : "Work Management - Team Member ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/work-management---team-member.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Work Management - Team Member ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Insights overview ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/work-management---team-member/insights-overview.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Work Management - Team Member \/ Insights overview ", 
"snippet" : "OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards....", 
"body" : "[video] OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards. " }, 
{ "title" : "Update Timesheets ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/work-management---team-member/update-timesheets.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Work Management - Team Member \/ Update Timesheets ", 
"snippet" : "You have the plan, now what? Leverage OnePlan’s powerful time tracking capabilities to ensure your teams are focused on the right work...", 
"body" : "[video] You have the plan, now what? Leverage OnePlan’s powerful time tracking capabilities to ensure your teams are focused on the right work " }, 
{ "title" : "Manage My Work ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/work-management---team-member/manage-my-work.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Work Management - Team Member \/ Manage My Work ", 
"snippet" : "To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams....", 
"body" : "[video] To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams. " }, 
{ "title" : "Create new Ideas ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/work-management---team-member/create-new-ideas.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Work Management - Team Member \/ Create new Ideas ", 
"snippet" : "Enable the ability to capture project requests, new ideas, and work without suffering from intake overload. Manage work demand through scoring and prioritization of the requests that bring the most value...", 
"body" : "[video] Enable the ability to capture project requests, new ideas, and work without suffering from intake overload. Manage work demand through scoring and prioritization of the requests that bring the most value " }, 
{ "title" : "Reporting - Executives ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/reporting---executives.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Reporting - Executives ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "View Reports and Dashboards ", 
"url" : "adaptive-project-and-portfolio-management-trial-guide/reporting---executives/view-reports-and-dashboards.html", 
"breadcrumbs" : "Use OnePlan \/ Adaptive Project and Portfolio Management Trial Guide \/ Reporting - Executives \/ View Reports and Dashboards ", 
"snippet" : "Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions...", 
"body" : "[video] Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions " }, 
{ "title" : "Strategic Portfolio Management Trial Guide ", 
"url" : "strategic-portfolio-management-trial-guide.html", 
"breadcrumbs" : "Use OnePlan \/ Strategic Portfolio Management Trial Guide ", 
"snippet" : "This role-based trial guide will assist you and your team through your OnePlan trial. Also see our full user guides for more information. Whether your portfolios consist of products, services or projects, strategic portfolio management means being able to change direction regularly and rapidly, base...", 
"body" : "This role-based trial guide will assist you and your team through your OnePlan trial. Also see our full user guides for more information. Whether your portfolios consist of products, services or projects, strategic portfolio management means being able to change direction regularly and rapidly, based on trustworthy data that is easily visible and complete. It means having measurable goals and strategies (objectives and key results, or OKRs), followed by aligning ideas and activities to those OKRs. Finally, it requires making good decisions on the sequencing and re-sequencing of your initiatives based on metrics of value, capacity and business performance. " }, 
{ "title" : "In this section ", 
"url" : "strategic-portfolio-management-trial-guide.html#UUID-504b9d44-6371-9b62-aa46-ddf33d5fda8f_section-idm4527084823672032878041653851", 
"breadcrumbs" : "Use OnePlan \/ Strategic Portfolio Management Trial Guide \/ In this section ", 
"snippet" : "Reporting - Executives View Reports and DashboardsManage corporate strategyWork Management - Team Member Insights overviewManage My Work...", 
"body" : "Reporting - Executives View Reports and DashboardsManage corporate strategyWork Management - Team Member Insights overviewManage My Work" }, 
{ "title" : "Reporting - Executives ", 
"url" : "strategic-portfolio-management-trial-guide/reporting---executives.html", 
"breadcrumbs" : "Use OnePlan \/ Strategic Portfolio Management Trial Guide \/ Reporting - Executives ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "View Reports and Dashboards ", 
"url" : "strategic-portfolio-management-trial-guide/reporting---executives/view-reports-and-dashboards.html", 
"breadcrumbs" : "Use OnePlan \/ Strategic Portfolio Management Trial Guide \/ Reporting - Executives \/ View Reports and Dashboards ", 
"snippet" : "Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions...", 
"body" : "[video] Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions " }, 
{ "title" : "Manage corporate strategy ", 
"url" : "strategic-portfolio-management-trial-guide/reporting---executives/manage-corporate-strategy.html", 
"breadcrumbs" : "Use OnePlan \/ Strategic Portfolio Management Trial Guide \/ Reporting - Executives \/ Manage corporate strategy ", 
"snippet" : "Connect long-term business strategy, goals\/OKRs and results to adapt and thrive....", 
"body" : "[video] Connect long-term business strategy, goals\/OKRs and results to adapt and thrive. " }, 
{ "title" : "Work Management - Team Member ", 
"url" : "strategic-portfolio-management-trial-guide/work-management---team-member.html", 
"breadcrumbs" : "Use OnePlan \/ Strategic Portfolio Management Trial Guide \/ Work Management - Team Member ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Insights overview ", 
"url" : "strategic-portfolio-management-trial-guide/work-management---team-member/insights-overview.html", 
"breadcrumbs" : "Use OnePlan \/ Strategic Portfolio Management Trial Guide \/ Work Management - Team Member \/ Insights overview ", 
"snippet" : "OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards....", 
"body" : "[video] OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards. " }, 
{ "title" : "Manage My Work ", 
"url" : "strategic-portfolio-management-trial-guide/work-management---team-member/manage-my-work.html", 
"breadcrumbs" : "Use OnePlan \/ Strategic Portfolio Management Trial Guide \/ Work Management - Team Member \/ Manage My Work ", 
"snippet" : "To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams....", 
"body" : "[video] To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams. " }, 
{ "title" : "Professional Services Automation Trial Guide ", 
"url" : "professional-services-automation-trial-guide.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide ", 
"snippet" : "This role-based trial guide will assist you and your team through your OnePlan trial. Also see our full user guides for more information. OnePlan’s Professional Services Automation is an end-to-end solution that provides service delivery organizations a single system of engagement for sales, resourc...", 
"body" : "This role-based trial guide will assist you and your team through your OnePlan trial. Also see our full user guides for more information. OnePlan’s Professional Services Automation is an end-to-end solution that provides service delivery organizations a single system of engagement for sales, resourcing, delivery, and billing. Streamline your delivery with workflows that align with every phase of the customer lifecycle. From customer acquisition to operational support, OnePlan’s PSA solution drives productivity, enabling teams to get the data they need to run the business optimally and make the right decisions. " }, 
{ "title" : "In this section ", 
"url" : "professional-services-automation-trial-guide.html#UUID-b533b17d-2d1c-e6ac-d471-352d661df4a1_section-idm452708468441443287805353271", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ In this section ", 
"snippet" : "Project Management - Project Manager Create a new PlanManage Plan DetailsManage the Work Plan in ListsManage the Work Plan in BoardsManage Resource PlansManage Financial PlansInsights overviewView Reports and DashboardsPortfolio Management - Portfolio Manager Monitor and prioritize your Portfolio ov...", 
"body" : "Project Management - Project Manager Create a new PlanManage Plan DetailsManage the Work Plan in ListsManage the Work Plan in BoardsManage Resource PlansManage Financial PlansInsights overviewView Reports and DashboardsPortfolio Management - Portfolio Manager Monitor and prioritize your Portfolio overviewView Reports and DashboardsInsights overviewResource Management - Resource Manager Manage Resource PlansManage resource schedulesResource Center overviewWork Management - Team Member Insights overviewUpdate TimesheetsManage My Work" }, 
{ "title" : "Project Management - Project Manager ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Create a new Plan ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/create-a-new-plan.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Create a new Plan ", 
"snippet" : "This article explains how to create a new plan.  A \"plan\" is a general term that may be used for something to be managed and\/or analyzed.  Such as projects, epics, portfolios, programs, initiatives, etc.  OnePlan users who are in the permissions groups Contributor, Manager, or Owner can create new p...", 
"body" : "This article explains how to create a new plan.  A \"plan\" is a general term that may be used for something to be managed and\/or analyzed.  Such as projects, epics, portfolios, programs, initiatives, etc.  OnePlan users who are in the permissions groups Contributor, Manager, or Owner can create new plans. " }, 
{ "title" : "Portfolios Page ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2e7d514d-94af-6dc9-e5f7-e52b1591c10e_id_getting-started-page", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Portfolios Page ", 
"snippet" : "Create a new plan from the Portfolios page. Click the New Plan menu, then select the desired plan type. You may see multiple plan types or just \"New Plan,\" depending how your trial site was set up....", 
"body" : "Create a new plan from the Portfolios page. Click the New Plan menu, then select the desired plan type. You may see multiple plan types or just \"New Plan,\" depending how your trial site was set up. " }, 
{ "title" : "Example Plan Types ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2e7d514d-94af-6dc9-e5f7-e52b1591c10e_id_example-plan-types", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Portfolios Page \/ Example Plan Types ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Plan Name ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2e7d514d-94af-6dc9-e5f7-e52b1591c10e_id_plan-name", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Plan Name ", 
"snippet" : "First, enter the new plan name, such as Office365 Launch . Click Add Plan. Then, you will be directed to the Plan Details page....", 
"body" : "First, enter the new plan name, such as Office365 Launch . Click Add Plan. Then, you will be directed to the Plan Details page. " }, 
{ "title" : "Plan Details ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2e7d514d-94af-6dc9-e5f7-e52b1591c10e_id_new-plan-form", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Plan Details ", 
"snippet" : "Complete the plan's details. Your form may have different fields & different stages, based on your organization's use case & configuration. The page is editable and you may always return to the Details page throughout the life of the plan. When you make a change, it is saved automatically....", 
"body" : "Complete the plan's details. Your form may have different fields & different stages, based on your organization's use case & configuration. The page is editable and you may always return to the Details page throughout the life of the plan. When you make a change, it is saved automatically. " }, 
{ "title" : "Enter Prioritization Fields ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2e7d514d-94af-6dc9-e5f7-e52b1591c10e_id_enter-prioritization-fields", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Plan Details \/ Enter Prioritization Fields ", 
"snippet" : "For the purpose of later doing prioritization & portfolio analysis, be sure to complete the prioritization fields for your plan. There are traditional prioritization and also SAF agile prioritization type fields....", 
"body" : "For the purpose of later doing prioritization & portfolio analysis, be sure to complete the prioritization fields for your plan. There are traditional prioritization and also SAF agile prioritization type fields. " }, 
{ "title" : "Move Plan to the Next Stage ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2e7d514d-94af-6dc9-e5f7-e52b1591c10e_id_move-plan-to-the-next-stage", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Plan Details \/ Enter Prioritization Fields \/ Move Plan to the Next Stage ", 
"snippet" : "When ready to move your plan to the next stage, Click on the stage name to visually see the current stage. The tab color changes to green on the current stage. Future stages are grey. Previous stages are blue. You would also want to change the stage field to the appropriate stage. The fields & apps ...", 
"body" : "When ready to move your plan to the next stage, Click on the stage name to visually see the current stage. The tab color changes to green on the current stage. Future stages are grey. Previous stages are blue. You would also want to change the stage field to the appropriate stage. The fields & apps available may be different at each stage of planning. " }, 
{ "title" : "Time to Plan! ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-2e7d514d-94af-6dc9-e5f7-e52b1591c10e_id_build-out-plan", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Time to Plan! ", 
"snippet" : "Build out your plan according to your planning preference. This trial guide will walk you through the following top down planning features: Build a Resource Plan Build a Financial Plan Do portfolio analysis...", 
"body" : "Build out your plan according to your planning preference. This trial guide will walk you through the following top down planning features: Build a Resource Plan Build a Financial Plan Do portfolio analysis " }, 
{ "title" : "Manage Plan Details ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/manage-plan-details.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Manage Plan Details ", 
"snippet" : "Manage your Plans meta data using the Plan Detail form....", 
"body" : "[video] Manage your Plans meta data using the Plan Detail form. " }, 
{ "title" : "Manage the Work Plan in Lists ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists ", 
"snippet" : "To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams....", 
"body" : "To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams. " }, 
{ "title" : "OnePlan's Work Plan ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-b1ad883f-e31a-4f58-a9c0-0ccb58dd2614_section-idm4671155326905632715967479364", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ OnePlan's Work Plan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Microsoft Project Desktop and OnePlan ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-b1ad883f-e31a-4f58-a9c0-0ccb58dd2614_section-idm4483122699662432715968747471", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ Microsoft Project Desktop and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Project for the web and OnePlan ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-b1ad883f-e31a-4f58-a9c0-0ccb58dd2614_section-idm4592941179484832715969732862", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ Project for the web and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Microsoft Planner and OnePlan ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-b1ad883f-e31a-4f58-a9c0-0ccb58dd2614_section-idm459294117542083271597040602", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ Microsoft Planner and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Azure DevOps and OnePlan ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-b1ad883f-e31a-4f58-a9c0-0ccb58dd2614_section-idm4671155347873632715971846753", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ Azure DevOps and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Manage the Work Plan in Boards ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/manage-the-work-plan-in-boards.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Boards ", 
"snippet" : "Visually manage work using Kanban boards with the flexibility to easily model any workflow process, regardless of complexity....", 
"body" : "[video] Visually manage work using Kanban boards with the flexibility to easily model any workflow process, regardless of complexity. " }, 
{ "title" : "Manage Resource Plans ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/manage-resource-plans.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Manage Resource Plans ", 
"snippet" : "Optimize your resource capacity and improve utilization. OnePlan’s Resource Plan delivers a combined view to balance demand and capacity across teams, roles, and named resources....", 
"body" : "[video] Optimize your resource capacity and improve utilization. OnePlan’s Resource Plan delivers a combined view to balance demand and capacity across teams, roles, and named resources. " }, 
{ "title" : "Manage Financial Plans ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/manage-financial-plans.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Manage Financial Plans ", 
"snippet" : "OnePlan connects financials from strategy to investments to detailed budget, actuals, and forecast.  Gain an understanding of project investment to value realization within capital and expense constraints....", 
"body" : "[video] OnePlan connects financials from strategy to investments to detailed budget, actuals, and forecast.  Gain an understanding of project investment to value realization within capital and expense constraints. " }, 
{ "title" : "Insights overview ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/insights-overview.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ Insights overview ", 
"snippet" : "OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards....", 
"body" : "[video] OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards. " }, 
{ "title" : "View Reports and Dashboards ", 
"url" : "professional-services-automation-trial-guide/project-management---project-manager/view-reports-and-dashboards.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Project Management - Project Manager \/ View Reports and Dashboards ", 
"snippet" : "Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions...", 
"body" : "[video] Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions " }, 
{ "title" : "Portfolio Management - Portfolio Manager ", 
"url" : "professional-services-automation-trial-guide/portfolio-management---portfolio-manager.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Portfolio Management - Portfolio Manager ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Monitor and prioritize your Portfolio overview ", 
"url" : "professional-services-automation-trial-guide/portfolio-management---portfolio-manager/monitor-and-prioritize-your-portfolio-overview.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Portfolio Management - Portfolio Manager \/ Monitor and prioritize your Portfolio overview ", 
"snippet" : "Translate strategy into delivery on an organization-wide, cross-functional scale with a portfolio that connect the investments, outcomes, business capabilities, milestones, technology and financials required to realize strategies....", 
"body" : "[video] Translate strategy into delivery on an organization-wide, cross-functional scale with a portfolio that connect the investments, outcomes, business capabilities, milestones, technology and financials required to realize strategies. " }, 
{ "title" : "View Reports and Dashboards ", 
"url" : "professional-services-automation-trial-guide/portfolio-management---portfolio-manager/view-reports-and-dashboards.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Portfolio Management - Portfolio Manager \/ View Reports and Dashboards ", 
"snippet" : "Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions...", 
"body" : "[video] Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions " }, 
{ "title" : "Insights overview ", 
"url" : "professional-services-automation-trial-guide/portfolio-management---portfolio-manager/insights-overview.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Portfolio Management - Portfolio Manager \/ Insights overview ", 
"snippet" : "OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards....", 
"body" : "[video] OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards. " }, 
{ "title" : "Resource Management - Resource Manager ", 
"url" : "professional-services-automation-trial-guide/resource-management---resource-manager.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Resource Management - Resource Manager ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Manage Resource Plans ", 
"url" : "professional-services-automation-trial-guide/resource-management---resource-manager/manage-resource-plans.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Resource Management - Resource Manager \/ Manage Resource Plans ", 
"snippet" : "Optimize your resource capacity and improve utilization. OnePlan’s Resource Plan delivers a combined view to balance demand and capacity across teams, roles, and named resources....", 
"body" : "[video] Optimize your resource capacity and improve utilization. OnePlan’s Resource Plan delivers a combined view to balance demand and capacity across teams, roles, and named resources. " }, 
{ "title" : "Manage resource schedules ", 
"url" : "professional-services-automation-trial-guide/resource-management---resource-manager/manage-resource-schedules.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Resource Management - Resource Manager \/ Manage resource schedules ", 
"snippet" : "Proactively identify resource bottlenecks by role, business unit and other key factors to uncover issues before impacting the plan....", 
"body" : "[video] Proactively identify resource bottlenecks by role, business unit and other key factors to uncover issues before impacting the plan. " }, 
{ "title" : "Resource Center overview ", 
"url" : "professional-services-automation-trial-guide/resource-management---resource-manager/resource-center-overview.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Resource Management - Resource Manager \/ Resource Center overview ", 
"snippet" : "Invite users and manage a pool of resource using the Resource Center...", 
"body" : "[video] Invite users and manage a pool of resource using the Resource Center " }, 
{ "title" : "Work Management - Team Member ", 
"url" : "professional-services-automation-trial-guide/work-management---team-member.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Work Management - Team Member ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Insights overview ", 
"url" : "professional-services-automation-trial-guide/work-management---team-member/insights-overview.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Work Management - Team Member \/ Insights overview ", 
"snippet" : "OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards....", 
"body" : "[video] OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards. " }, 
{ "title" : "Update Timesheets ", 
"url" : "professional-services-automation-trial-guide/work-management---team-member/update-timesheets.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Work Management - Team Member \/ Update Timesheets ", 
"snippet" : "You have the plan, now what? Leverage OnePlan’s powerful time tracking capabilities to ensure your teams are focused on the right work...", 
"body" : "[video] You have the plan, now what? Leverage OnePlan’s powerful time tracking capabilities to ensure your teams are focused on the right work " }, 
{ "title" : "Manage My Work ", 
"url" : "professional-services-automation-trial-guide/work-management---team-member/manage-my-work.html", 
"breadcrumbs" : "Use OnePlan \/ Professional Services Automation Trial Guide \/ Work Management - Team Member \/ Manage My Work ", 
"snippet" : "To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams....", 
"body" : "[video] To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams. " }, 
{ "title" : "Collaborative Work Management Trial Guide ", 
"url" : "collaborative-work-management-trial-guide.html", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide ", 
"snippet" : "This role-based trial guide will assist you and your team through your OnePlan trial. Also see our full user guides for more information. OnePlan provides a powerful work management solution in Teams to bring visibility inot all work across the organization. We provide the power to make projec t and...", 
"body" : "This role-based trial guide will assist you and your team through your OnePlan trial. Also see our full user guides for more information. OnePlan provides a powerful work management solution in Teams to bring visibility inot all work across the organization. We provide the power to make projec t and work management simple. " }, 
{ "title" : "In this section ", 
"url" : "collaborative-work-management-trial-guide.html#UUID-cb832023-c9b3-049d-575d-f07731efa8b3_section-idm4573377323582432878094256389", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ In this section ", 
"snippet" : "Project Management - Project Manager Create a new PlanManage Plan DetailsManage the Work Plan in ListsManage the Work Plan in BoardsInsights overviewView Reports and DashboardsWork Management - Team Member Insights overviewManage My WorkReporting - Executives View Reports and Dashboards...", 
"body" : "Project Management - Project Manager Create a new PlanManage Plan DetailsManage the Work Plan in ListsManage the Work Plan in BoardsInsights overviewView Reports and DashboardsWork Management - Team Member Insights overviewManage My WorkReporting - Executives View Reports and Dashboards" }, 
{ "title" : "Project Management - Project Manager ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager.html", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Create a new Plan ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/create-a-new-plan.html", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan ", 
"snippet" : "This article explains how to create a new plan.  A \"plan\" is a general term that may be used for something to be managed and\/or analyzed.  Such as projects, epics, portfolios, programs, initiatives, etc.  OnePlan users who are in the permissions groups Contributor, Manager, or Owner can create new p...", 
"body" : "This article explains how to create a new plan.  A \"plan\" is a general term that may be used for something to be managed and\/or analyzed.  Such as projects, epics, portfolios, programs, initiatives, etc.  OnePlan users who are in the permissions groups Contributor, Manager, or Owner can create new plans. " }, 
{ "title" : "Portfolios Page ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-439278fe-818e-ba81-71a0-c6a395328182_id_getting-started-page", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Portfolios Page ", 
"snippet" : "Create a new plan from the Portfolios page. Click the New Plan menu, then select the desired plan type. You may see multiple plan types or just \"New Plan,\" depending how your trial site was set up....", 
"body" : "Create a new plan from the Portfolios page. Click the New Plan menu, then select the desired plan type. You may see multiple plan types or just \"New Plan,\" depending how your trial site was set up. " }, 
{ "title" : "Example Plan Types ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-439278fe-818e-ba81-71a0-c6a395328182_id_example-plan-types", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Portfolios Page \/ Example Plan Types ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Plan Name ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-439278fe-818e-ba81-71a0-c6a395328182_id_plan-name", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Plan Name ", 
"snippet" : "First, enter the new plan name, such as Office365 Launch . Click Add Plan. Then, you will be directed to the Plan Details page....", 
"body" : "First, enter the new plan name, such as Office365 Launch . Click Add Plan. Then, you will be directed to the Plan Details page. " }, 
{ "title" : "Plan Details ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-439278fe-818e-ba81-71a0-c6a395328182_id_new-plan-form", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Plan Details ", 
"snippet" : "Complete the plan's details. Your form may have different fields & different stages, based on your organization's use case & configuration. The page is editable and you may always return to the Details page throughout the life of the plan. When you make a change, it is saved automatically....", 
"body" : "Complete the plan's details. Your form may have different fields & different stages, based on your organization's use case & configuration. The page is editable and you may always return to the Details page throughout the life of the plan. When you make a change, it is saved automatically. " }, 
{ "title" : "Enter Prioritization Fields ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-439278fe-818e-ba81-71a0-c6a395328182_id_enter-prioritization-fields", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Plan Details \/ Enter Prioritization Fields ", 
"snippet" : "For the purpose of later doing prioritization & portfolio analysis, be sure to complete the prioritization fields for your plan. There are traditional prioritization and also SAF agile prioritization type fields....", 
"body" : "For the purpose of later doing prioritization & portfolio analysis, be sure to complete the prioritization fields for your plan. There are traditional prioritization and also SAF agile prioritization type fields. " }, 
{ "title" : "Move Plan to the Next Stage ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-439278fe-818e-ba81-71a0-c6a395328182_id_move-plan-to-the-next-stage", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Plan Details \/ Enter Prioritization Fields \/ Move Plan to the Next Stage ", 
"snippet" : "When ready to move your plan to the next stage, Click on the stage name to visually see the current stage. The tab color changes to green on the current stage. Future stages are grey. Previous stages are blue. You would also want to change the stage field to the appropriate stage. The fields & apps ...", 
"body" : "When ready to move your plan to the next stage, Click on the stage name to visually see the current stage. The tab color changes to green on the current stage. Future stages are grey. Previous stages are blue. You would also want to change the stage field to the appropriate stage. The fields & apps available may be different at each stage of planning. " }, 
{ "title" : "Time to Plan! ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/create-a-new-plan.html#UUID-439278fe-818e-ba81-71a0-c6a395328182_id_build-out-plan", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Create a new Plan \/ Time to Plan! ", 
"snippet" : "Build out your plan according to your planning preference. This trial guide will walk you through the following top down planning features: Build a Resource Plan Build a Financial Plan Do portfolio analysis...", 
"body" : "Build out your plan according to your planning preference. This trial guide will walk you through the following top down planning features: Build a Resource Plan Build a Financial Plan Do portfolio analysis " }, 
{ "title" : "Manage Plan Details ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/manage-plan-details.html", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Manage Plan Details ", 
"snippet" : "Manage your Plans meta data using the Plan Detail form....", 
"body" : "[video] Manage your Plans meta data using the Plan Detail form. " }, 
{ "title" : "Manage the Work Plan in Lists ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists ", 
"snippet" : "To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams....", 
"body" : "To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams. " }, 
{ "title" : "OnePlan's Work Plan ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-43d35936-b6c9-68b5-c6c3-20ee5eef6c58_section-idm4671155326905632715967479364", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ OnePlan's Work Plan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Microsoft Project Desktop and OnePlan ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-43d35936-b6c9-68b5-c6c3-20ee5eef6c58_section-idm4483122699662432715968747471", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ Microsoft Project Desktop and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Project for the web and OnePlan ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-43d35936-b6c9-68b5-c6c3-20ee5eef6c58_section-idm4592941179484832715969732862", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ Project for the web and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Microsoft Planner and OnePlan ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-43d35936-b6c9-68b5-c6c3-20ee5eef6c58_section-idm459294117542083271597040602", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ Microsoft Planner and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Azure DevOps and OnePlan ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-lists.html#UUID-43d35936-b6c9-68b5-c6c3-20ee5eef6c58_section-idm4671155347873632715971846753", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Lists \/ Azure DevOps and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Manage the Work Plan in Boards ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/manage-the-work-plan-in-boards.html", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Manage the Work Plan in Boards ", 
"snippet" : "Visually manage work using Kanban boards with the flexibility to easily model any workflow process, regardless of complexity....", 
"body" : "[video] Visually manage work using Kanban boards with the flexibility to easily model any workflow process, regardless of complexity. " }, 
{ "title" : "Insights overview ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/insights-overview.html", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ Insights overview ", 
"snippet" : "OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards....", 
"body" : "[video] OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards. " }, 
{ "title" : "View Reports and Dashboards ", 
"url" : "collaborative-work-management-trial-guide/project-management---project-manager/view-reports-and-dashboards.html", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Project Management - Project Manager \/ View Reports and Dashboards ", 
"snippet" : "Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions...", 
"body" : "[video] Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions " }, 
{ "title" : "Work Management - Team Member ", 
"url" : "collaborative-work-management-trial-guide/work-management---team-member.html", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Work Management - Team Member ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Insights overview ", 
"url" : "collaborative-work-management-trial-guide/work-management---team-member/insights-overview.html", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Work Management - Team Member \/ Insights overview ", 
"snippet" : "OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards....", 
"body" : "[video] OnePlan’s Insights AI helps drive governance and adoption of your portfolio management standards. " }, 
{ "title" : "Manage My Work ", 
"url" : "collaborative-work-management-trial-guide/work-management---team-member/manage-my-work.html", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Work Management - Team Member \/ Manage My Work ", 
"snippet" : "To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams....", 
"body" : "[video] To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams. " }, 
{ "title" : "Reporting - Executives ", 
"url" : "collaborative-work-management-trial-guide/reporting---executives.html", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Reporting - Executives ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "View Reports and Dashboards ", 
"url" : "collaborative-work-management-trial-guide/reporting---executives/view-reports-and-dashboards.html", 
"breadcrumbs" : "Use OnePlan \/ Collaborative Work Management Trial Guide \/ Reporting - Executives \/ View Reports and Dashboards ", 
"snippet" : "Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions...", 
"body" : "[video] Monitor your portfolio, projects and work to get answers quickly and empower your team to make confident decisions " }
]
$(document).trigger('search.ready');
});