$(document).ready(function () {indexDict['en'] = [{ "title" : "In-Product Help ", 
"url" : "in-product-help.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help ", 
"snippet" : "...", 
"body" : "" }, 
{ "title" : "Begin in OnePlan ", 
"url" : "in-product-help/begin-in-oneplan.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Begin in OnePlan ", 
"snippet" : "This article explains how to access OnePlan....", 
"body" : "This article explains how to access OnePlan. " }, 
{ "title" : "Login ", 
"url" : "in-product-help/begin-in-oneplan.html#UUID-8ff11fe6-4c01-34d6-d9e1-4cb74d678d45_UUID-e8ede622-62aa-bb38-2807-7cbd09c0c3a1", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Begin in OnePlan \/ Login ", 
"snippet" : "Go to https:\/\/my.oneplan.ai Your access to OnePlan is tied to your Office365 account. Log in with your Office365 user name and password....", 
"body" : "Go to https:\/\/my.oneplan.ai Your access to OnePlan is tied to your Office365 account. Log in with your Office365 user name and password. " }, 
{ "title" : "Getting Started ", 
"url" : "in-product-help/begin-in-oneplan.html#UUID-8ff11fe6-4c01-34d6-d9e1-4cb74d678d45_UUID-ec511ab0-f58d-744d-0911-08c620cb102f", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Begin in OnePlan \/ Getting Started ", 
"snippet" : "The first time you log into OnePlan, you are directed to the Getting Started \"Welcome to OnePlan\" page. This page includes an intro video to get you familiar with OnePlan. Going forward, OnePlan will remember your last screen and open there each time you log in. To return to the Getting Started page...", 
"body" : "The first time you log into OnePlan, you are directed to the Getting Started \"Welcome to OnePlan\" page. This page includes an intro video to get you familiar with OnePlan. Going forward, OnePlan will remember your last screen and open there each time you log in. To return to the Getting Started page at anytime, Click on the Help Menu ( ? ). Select Getting Started . " }, 
{ "title" : "Manage Financial Plans ", 
"url" : "in-product-help/manage-financial-plans.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Manage Financial Plans ", 
"snippet" : "OnePlan connects financials from strategy to investments to detailed budget, actuals, and forecast.  Gain an understanding of project investment to value realization within capital and expense constraints....", 
"body" : "[video] OnePlan connects financials from strategy to investments to detailed budget, actuals, and forecast.  Gain an understanding of project investment to value realization within capital and expense constraints. " }, 
{ "title" : "Manage the Work Plan in Boards ", 
"url" : "in-product-help/manage-the-work-plan-in-boards.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Manage the Work Plan in Boards ", 
"snippet" : "Visually manage work using Kanban boards with the flexibility to easily model any workflow process, regardless of complexity....", 
"body" : "[video] Visually manage work using Kanban boards with the flexibility to easily model any workflow process, regardless of complexity. " }, 
{ "title" : "Manage My Work ", 
"url" : "in-product-help/manage-my-work.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Manage My Work ", 
"snippet" : "To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams....", 
"body" : "[video] To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams. " }, 
{ "title" : "Manage Plan Details ", 
"url" : "in-product-help/manage-plan-details.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Manage Plan Details ", 
"snippet" : "Manage your Plans meta data using the Plan Detail form....", 
"body" : "[video] Manage your Plans meta data using the Plan Detail form. " }, 
{ "title" : "Monitor and prioritize your Portfolio overview ", 
"url" : "in-product-help/monitor-and-prioritize-your-portfolio-overview.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Monitor and prioritize your Portfolio overview ", 
"snippet" : "Translate strategy into delivery on an organization-wide, cross-functional scale with a portfolio that connect the investments, outcomes, business capabilities, milestones, technology and financials required to realize strategies....", 
"body" : "[video] Translate strategy into delivery on an organization-wide, cross-functional scale with a portfolio that connect the investments, outcomes, business capabilities, milestones, technology and financials required to realize strategies. " }, 
{ "title" : "Resource Center overview ", 
"url" : "in-product-help/resource-center-overview.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Resource Center overview ", 
"snippet" : "Invite users and manage a pool of resource using the Resource Center...", 
"body" : "[video] Invite users and manage a pool of resource using the Resource Center " }, 
{ "title" : "Manage Resource Plans ", 
"url" : "in-product-help/manage-resource-plans.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Manage Resource Plans ", 
"snippet" : "Optimize your resource capacity and improve utilization. OnePlan’s Resource Plan delivers a combined view to balance demand and capacity across teams, roles, and named resources....", 
"body" : "[video] Optimize your resource capacity and improve utilization. OnePlan’s Resource Plan delivers a combined view to balance demand and capacity across teams, roles, and named resources. " }, 
{ "title" : "Manage Work Plan Schedules ", 
"url" : "in-product-help/manage-work-plan-schedules.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Manage Work Plan Schedules ", 
"snippet" : "Proactively identify resource bottlenecks by role, business unit and other key factors to uncover issues before impacting the plan....", 
"body" : "[video] Proactively identify resource bottlenecks by role, business unit and other key factors to uncover issues before impacting the plan. " }, 
{ "title" : "Update Status Reports ", 
"url" : "in-product-help/update-status-reports.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Update Status Reports ", 
"snippet" : "OnePlan’s Status Reports help you, your stakeholders, and internal team stay honest about your work, process, budgets, and issues....", 
"body" : "[video] OnePlan’s Status Reports help you, your stakeholders, and internal team stay honest about your work, process, budgets, and issues. " }, 
{ "title" : "Update Timesheets ", 
"url" : "in-product-help/update-timesheets.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Update Timesheets ", 
"snippet" : "You have the plan, now what? Leverage OnePlan’s powerful time tracking capabilities to ensure your teams are focused on the right work...", 
"body" : "[video] You have the plan, now what? Leverage OnePlan’s powerful time tracking capabilities to ensure your teams are focused on the right work " }, 
{ "title" : "Manage the Work Plan in Lists ", 
"url" : "in-product-help/manage-the-work-plan-in-lists.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Manage the Work Plan in Lists ", 
"snippet" : "To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams....", 
"body" : "To maximize productivity, teams must work the way they work best. In every organization there are specific tools that meet the needs of each line of work which leads to segregated tools and disconnected teams. " }, 
{ "title" : "OnePlan's Work Plan ", 
"url" : "in-product-help/manage-the-work-plan-in-lists.html#UUID-62d73048-2c44-2e19-c377-b3870240261e_section-idm4671155326905632715967479364", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Manage the Work Plan in Lists \/ OnePlan's Work Plan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Microsoft Project Desktop and OnePlan ", 
"url" : "in-product-help/manage-the-work-plan-in-lists.html#UUID-62d73048-2c44-2e19-c377-b3870240261e_section-idm4483122699662432715968747471", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Manage the Work Plan in Lists \/ Microsoft Project Desktop and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Project for the web and OnePlan ", 
"url" : "in-product-help/manage-the-work-plan-in-lists.html#UUID-62d73048-2c44-2e19-c377-b3870240261e_section-idm4592941179484832715969732862", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Manage the Work Plan in Lists \/ Project for the web and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Microsoft Planner and OnePlan ", 
"url" : "in-product-help/manage-the-work-plan-in-lists.html#UUID-62d73048-2c44-2e19-c377-b3870240261e_section-idm459294117542083271597040602", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Manage the Work Plan in Lists \/ Microsoft Planner and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Azure DevOps and OnePlan ", 
"url" : "in-product-help/manage-the-work-plan-in-lists.html#UUID-62d73048-2c44-2e19-c377-b3870240261e_section-idm4671155347873632715971846753", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Manage the Work Plan in Lists \/ Azure DevOps and OnePlan ", 
"snippet" : "...", 
"body" : "[video] " }, 
{ "title" : "Create new Ideas ", 
"url" : "in-product-help/create-new-ideas.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Create new Ideas ", 
"snippet" : "Enable the ability to capture project requests, new ideas, and work without suffering from intake overload. Manage work demand through scoring and prioritization of the requests that bring the most value,...", 
"body" : "[video] Enable the ability to capture project requests, new ideas, and work without suffering from intake overload. Manage work demand through scoring and prioritization of the requests that bring the most value, " }, 
{ "title" : "Manage corporate strategy ", 
"url" : "in-product-help/manage-corporate-strategy.html", 
"breadcrumbs" : "Use OnePlan \/ In-Product Help \/ Manage corporate strategy ", 
"snippet" : "Connect long-term business strategy, goals\/OKRs and results to adapt and thrive....", 
"body" : "[video] Connect long-term business strategy, goals\/OKRs and results to adapt and thrive. " }
]
$(document).trigger('search.ready');
});